# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wEuTfpNvf16GssdQ8kOxHZVr7X48tSRj

# BreakHis Dataset Analysis

End-to-end pipeline for breast cancer histopathology classification

## Environment & Reproducibility

- Random seed set to 42  
- Libraries used: numpy, pandas, matplotlib, seaborn, torch, cv2  
- Model training was performed using a Tesla T4 GPU in Google Colab.
- The notebook runs end-to-end without manual intervention

## Dataset Source

Dataset Source: BreakHis dataset from UFPR (Federal University of Paraná)
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import cv2
import torch

random.seed(42)
np.random.seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

dataset_path = "/content/drive/MyDrive/BreaKHis_v1/histology_slides/breast"

image_paths = []

for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.endswith(".png"):
            image_paths.append(os.path.join(root, file))

print("Total images:", len(image_paths))

data = []

for path in image_paths:
    filename = os.path.basename(path)

    parts = filename.split("-")
    class_info = parts[0].split("_")

    label = class_info[1]
    subtype = class_info[2]

    patient_id = parts[1]
    magnification = parts[2]

    data.append({
        "path": path,
        "label": "benign" if label == "B" else "malignant",
        "subtype": subtype,
        "patient": patient_id,
        "magnification": magnification
    })

df = pd.DataFrame(data)
df.head()

"""### Column Description

- path: file path of the image  
- label: tumor class (benign or malignant)  
- subtype: tumor subtype  
- patient: patient identifier  
- magnification: zoom level of the image

## Exploratory Data Analysis (EDA)
"""

df.to_csv("/content/drive/MyDrive/breakhis_metadata.csv", index=False)

sns.countplot(data=df, x="label")
plt.title("Benign vs Malignant")
plt.show()

sns.countplot(data=df, x="magnification")
plt.title("Magnification Distribution")
plt.show()

plt.figure(figsize=(10,5))
sns.countplot(data=df, x="subtype")
plt.xticks(rotation=45)
plt.title("Tumor Subtypes")
plt.show()

"""### Observations

- The dataset shows class imbalance between benign and malignant images  
- Some tumor subtypes have fewer samples than others  
- Different magnification levels show noticeable visual differences
"""

sample_paths = random.sample(list(df["path"]), 8)

plt.figure(figsize=(10,10))

for i, path in enumerate(sample_paths):
    img = cv2.imread(path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    plt.subplot(2,4,i+1)
    plt.imshow(img)
    plt.axis("off")

plt.show()

from sklearn.model_selection import train_test_split

patients = df["patient"].unique()

if len(patients) < 2:
    raise ValueError("Not enough unique patients for a meaningful patient-level split. Minimum 2 patients required to form train/test sets.")
elif len(patients) == 2:

    print("Warning: Only 2 unique patients found. Performing a train/test split at the patient level without a separate validation patient set.")
    train_patients, test_patients = train_test_split(
        patients, test_size=0.5, random_state=42
    )
    val_patients = []
else:

    train_patients, temp_patients = train_test_split(
        patients, test_size=0.3, random_state=42
    )
    val_patients, test_patients = train_test_split(
        temp_patients, test_size=0.5, random_state=42
    )

train_df = df[df["patient"].isin(train_patients)]
val_df = df[df["patient"].isin(val_patients)]
test_df = df[df["patient"].isin(test_patients)]

print(f"Train patients: {train_patients}")
print(f"Validation patients: {val_patients}")
print(f"Test patients: {test_patients}")
print(f"Number of patients in train_df: {len(train_df['patient'].unique()) if not train_df.empty else 0}")
print(f"Number of patients in val_df: {len(val_df['patient'].unique()) if not val_df.empty else 0}")
print(f"Number of patients in test_df: {len(test_df['patient'].unique()) if not test_df.empty else 0}")

"""## Preprocessing

- Images resized to 128×128 pixels  
- Pixel values normalized to range [0,1]  
- Patient-wise split used to avoid data leakage
"""

train_df = train_df.sample(1500, random_state=42)
test_df = test_df.sample(min(300, len(test_df)), random_state=42)

from torch.utils.data import Dataset

class BreakHisDataset(Dataset):
    def __init__(self, df):
        self.df = df.reset_index(drop=True)

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        img = cv2.imread(row["path"])
        img = cv2.resize(img, (128,128))
        img = img / 255.0

        img = torch.tensor(img, dtype=torch.float32).permute(2,0,1)

        label = 0 if row["label"] == "benign" else 1

        return img, label

from torch.utils.data import DataLoader

train_dataset = BreakHisDataset(train_df)
test_dataset = BreakHisDataset(test_df)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False, num_workers=2)

"""## Model Development"""

import torch.nn as nn

class SimpleCNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv = nn.Sequential(
            nn.Conv2d(3,16,3,padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(16,32,3,padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(32*32*32, 128),
            nn.ReLU(),
            nn.Linear(128,2)
        )

    def forward(self, x):
        x = self.conv(x)
        x = self.fc(x)
        return x

model = SimpleCNN().to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

"""## Model Training"""

epochs = 2

for epoch in range(epochs):
    model.train()

    for i, (images, labels) in enumerate(train_loader):
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        if i % 50 == 0:
            print(f"Epoch {epoch+1}, Step {i}, Loss: {loss.item():.4f}")

    print(f"Epoch {epoch+1} DONE")

"""## Training Setup

- Optimizer: Adam  
- Learning rate: 0.001  
- Batch size: 16  
- Epochs: 2  
- Loss function: CrossEntropyLoss

## Model Evaluation
"""

from sklearn.metrics import classification_report, confusion_matrix

model.eval()

y_true = []
y_pred = []

with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)

        outputs = model(images)
        _, preds = torch.max(outputs, 1)

        y_true.extend(labels.numpy())
        y_pred.extend(preds.cpu().numpy())

print(classification_report(y_true, y_pred))
print(confusion_matrix(y_true, y_pred))

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Benign','Malignant'],
            yticklabels=['Benign','Malignant'])

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

"""## Ethical Considerations

Medical AI systems must be used cautiously. Incorrect predictions can have serious consequences, so results should not be used for clinical decision-making.
"""

from sklearn.metrics import roc_auc_score

probs = []
true = []

model.eval()

with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        outputs = model(images)
        prob = torch.softmax(outputs, dim=1)[:,1]

        probs.extend(prob.cpu().numpy())
        true.extend(labels.numpy())

print("ROC-AUC:", roc_auc_score(true, probs))

from sklearn.metrics import roc_curve

fpr, tpr, _ = roc_curve(true, probs)

plt.figure()
plt.plot(fpr, tpr)
plt.plot([0,1],[0,1],'--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.show()

wrong = []

model.eval()

with torch.no_grad():
    for i in range(len(test_dataset)):
        img, label = test_dataset[i]
        img_tensor = img.unsqueeze(0).to(device)

        output = model(img_tensor)
        pred = torch.argmax(output, dim=1).item()

        if pred != label:
            wrong.append((img, label, pred))

        if len(wrong) >= 6:
            break

plt.figure(figsize=(10,6))

for i, (img, label, pred) in enumerate(wrong):
    plt.subplot(2,3,i+1)
    plt.imshow(img.permute(1,2,0))
    plt.title(f"True:{label} Pred:{pred}")
    plt.axis("off")

plt.show()

"""## Evaluation Discussion

- The model achieves reasonable performance for a baseline CNN  
- Some misclassifications occur between benign and malignant classes  
- ROC-AUC score indicates the model has moderate ability to distinguish classes  
- Performance may vary across magnification levels

## Limitations

- Dataset has class imbalance  
- Limited number of patients reduces generalization  
- Reduced dataset used due to computational constraints  
- Simple CNN model may not capture complex patterns  
- Results are not suitable for clinical use

## Final Conclusion

This project successfully implemented an end-to-end machine learning pipeline for classifying breast cancer histopathology images.

The model achieved reasonable performance for a baseline CNN, while highlighting challenges such as class imbalance, limited patient data, and variability across magnification levels.

Future work could include transfer learning, larger datasets, and more advanced evaluation techniques.
"""
